### ISSUE TITLE
COPA template error

### ISSUE THREAD

**Issue by richardbaihe** [bigscience-workshop/promptsource#776] opened 2022-05-20 04:43 UTC
The template of superglue/copa "\u2026What could happen next, C1 or C2?" didn't deal with "cause" condition.

**Comment by stephenbach** [comment] 2022-05-23 15:09
Hi @richardbaihe, this is the expected behavior. Since it is a prompt asking about "what happens next," it is only applicable to the "effect" subset. It can be combined with the ...why? C1 or C2? prompt to cover the full set.

See https://github.com/bigscience-workshop/promptsource/blob/main/CONTRIBUTING.md#best-practices for more on skipping examples.

Closing for now. Please reopen if you have any followups. Thanks!

**Closed by stephenbach** 2022-05-23 15:09 UTC
