### ISSUE TITLE
Possibility to use custom datasets

### ISSUE THREAD

**Issue by lauritowal** [bigscience-workshop/promptsource#842] opened 2023-01-09 01:39 UTC
Hi - I have a custom dataset (e.g. https://huggingface.co/datasets/lauritowal/redefine-math) and would like to create prompts for it by using PromptSource:

```
-Download the repo
-Navigate to the root directory of the repo
-Run pip install -e . to install the promptsource module
```

It seems there is no option for loading a custom dataset into the tool via the Web-GUI. Maybe, I am missing something, but this would be a very helpful feature... (If there is a way to achieve this already, please let me know!)

Thanks!

**Comment by VictorSanh** [comment] 2023-01-09 14:36
Hi @lauritowal,

The easiest way there is right now is to include your user name into the list of additional user names to include in the toggle: https://github.com/bigscience-workshop/promptsource/blob/b860c0b2e06c027946d7ba874c83ef3cc101646a/promptsource/templates.py#L29

That way, your datasets will appear in promptsource. You can do that change locally since you are already installing from source.

**Comment by lauritowal** [comment] 2023-01-10 05:03
Wouldn't that require to have the a template.yml file in the TEMPLATES_FOLDER_PATH ? I don't have a template.yml file for my dataset above...

**Comment by lauritowal** [comment] 2023-01-11 01:31
Okay, I manually created one under /promptsource/templates/lauritowal/redefine_math/templates.yaml 

```
dataset: lauritowal/redefine_math
templates:
  02ff2949-0f45-4d97-941e-6fa4c0afbc2d: !Template
    answer_choices: 0 ||| 1
    id: 02ff2949-0f45-4d97-941e-6fa4c0afbc2f
    jinja: Question... {{text}} ||| {{ answer_choices [label] }}
    metadata: !TemplateMetadata
      choices_in_prompt: false
      languages:
      - en
      metrics:
      - Accuracy
      original_task: true
    name: Choices
    reference: ''
```

**Comment by VictorSanh** [comment] 2023-01-12 00:10
@lauritowal are you developing on a fork? i can help debug from there

**Comment by lauritowal** [comment] 2023-01-14 02:02
@VictorSanh sure, have a look at: https://github.com/NotTodAI/promptsource/commit/a0ac44c305516a58133770f681dec0bd47332c23
Thanks a lot!

**Comment by lauritowal** [comment] 2023-01-19 03:05
@VictorSanh did it work for you?

**Comment by lauritowal** [comment] 2023-01-19 20:14
Okay, seems like my dataset is not in datasets: https://huggingface.co/api/datasets?full=true

**Comment by VictorSanh** [comment] 2023-01-20 00:10
Indeed, that seems to be the root cause. I have asked internally why your dataset does appear in the result of the query. will get back to your tmrw morning, most of the team is in europe

**Comment by VictorSanh** [comment] 2023-01-20 00:32
Fixed!
`api/datasets/` is now paginated and your dataset was appearing on the 2nd page.
LMK if it works on your side!

**Comment by lauritowal** [comment] 2023-01-20 00:46
it works now, awesome! Thanks a lot @VictorSanh

**Comment by VictorSanh** [comment] 2023-01-20 15:06
amazing! closing this then

**Closed by VictorSanh** 2023-01-20 15:06 UTC
